// <auto-generated />
using System;
using MaqsData.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaqsData.Migrations
{
    [DbContext(typeof(DocumentContext))]
    partial class DocumentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MaqsData.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BraceletsSold")
                        .HasColumnType("int");

                    b.Property<int>("EarringsSold")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpensesForShow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Gkey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HairClipsSold")
                        .HasColumnType("int");

                    b.Property<int>("KeyChainsSold")
                        .HasColumnType("int");

                    b.Property<int>("NecklacesSold")
                        .HasColumnType("int");

                    b.Property<int>("RingsSold")
                        .HasColumnType("int");

                    b.Property<string>("ShowDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShowGrossProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShowNetProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MaqsData.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BraceletTotal")
                        .HasColumnType("int");

                    b.Property<decimal?>("BraceletTotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EarringTotal")
                        .HasColumnType("int");

                    b.Property<decimal?>("EarringTotalvalue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HairClipTotal")
                        .HasColumnType("int");

                    b.Property<decimal?>("HairClipTotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KeyChainTotal")
                        .HasColumnType("int");

                    b.Property<decimal?>("KeyChainTotalvalue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NeckalaceTotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NecklaceTotal")
                        .HasColumnType("int");

                    b.Property<int>("RingTotal")
                        .HasColumnType("int");

                    b.Property<decimal?>("RingTotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalInventoryValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("entryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Inventorys");
                });

            modelBuilder.Entity("MaqsData.Models.Total", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("YearOfTotals")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("YearToDateExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("YearToDateGrossProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("YearToDateNetProfit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Totals");
                });
#pragma warning restore 612, 618
        }
    }
}
